2023-10-04 20:34:09,214 - DEBUG - Using selector: EpollSelector
2023-10-04 20:34:17,775 - INFO - [Serveur] fonction prendre_commande utilisée au temps 8.561165571212769
2023-10-04 20:34:23,782 - INFO - [Pic] fonction ajouter utilisée au temps 14.567981481552124
2023-10-04 20:34:23,782 - INFO - [Serveur] fonction prendre_commande utilisée au temps 14.568456411361694
2023-10-04 20:34:23,783 - INFO - [Pic] fonction retirer utilisée au temps 14.56886076927185
2023-10-04 20:34:28,784 - INFO - [Barman] fonction prepare utilisée au temps 19.570045709609985
2023-10-04 20:34:28,784 - INFO - [Bar] fonction ajouter utilisée au temps 19.570473670959473
2023-10-04 20:34:29,784 - INFO - [Pic] fonction ajouter utilisée au temps 20.570504903793335
2023-10-04 20:34:29,785 - INFO - [Serveur] fonction prendre_commande utilisée au temps 20.571070432662964
2023-10-04 20:34:34,787 - INFO - [Pic] fonction retirer utilisée au temps 25.573394775390625
2023-10-04 20:34:35,787 - INFO - [Pic] fonction ajouter utilisée au temps 26.57349467277527
2023-10-04 20:34:39,786 - INFO - [Bar] fonction retirer utilisée au temps 30.57264804840088
2023-10-04 20:34:39,787 - INFO - [Serveur] fonction servir utilisée au temps 30.573288440704346
2023-10-04 20:34:39,788 - INFO - [Barman] fonction prepare utilisée au temps 30.57475185394287
2023-10-04 20:34:39,788 - INFO - [Bar] fonction ajouter utilisée au temps 30.574831247329712
2023-10-04 20:34:39,789 - INFO - [Pic] fonction retirer utilisée au temps 30.574902057647705
2023-10-04 20:34:40,789 - INFO - [Bar] fonction retirer utilisée au temps 31.57549500465393
2023-10-04 20:34:40,790 - INFO - [Serveur] fonction servir utilisée au temps 31.576197624206543
2023-10-04 20:34:44,791 - INFO - [Barman] fonction prepare utilisée au temps 35.57724142074585
2023-10-04 20:34:44,791 - INFO - [Bar] fonction ajouter utilisée au temps 35.57739877700806
2023-10-04 20:34:46,795 - INFO - [Serveur] fonction servir utilisée au temps 37.58083486557007
2023-10-04 20:34:47,806 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/./cocktail_asyncio.py:8> exception=SystemExit()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/./cocktail_asyncio.py", line 34, in main
    await asyncio.gather(*tasks3) #gère la concurrence
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 154, in servir
    sys.exit()
SystemExit
