2023-10-04 21:00:57,410 - DEBUG - Using selector: EpollSelector
2023-10-04 21:01:06,817 - INFO - [Serveur] fonction prendre_commande utilisée au temps 9.4071946144104
2023-10-04 21:01:07,819 - INFO - [Pic] fonction ajouter utilisée au temps 10.409173488616943
2023-10-04 21:01:07,820 - INFO - [Serveur] fonction prendre_commande utilisée au temps 10.409732818603516
2023-10-04 21:01:07,820 - INFO - [Pic] fonction retirer utilisée au temps 10.410184860229492
2023-10-04 21:01:08,821 - INFO - [Pic] fonction ajouter utilisée au temps 11.410500288009644
2023-10-04 21:01:08,821 - INFO - [Serveur] fonction prendre_commande utilisée au temps 11.41125202178955
2023-10-04 21:01:08,822 - INFO - [Barman] fonction prepare utilisée au temps 11.411785364151001
2023-10-04 21:01:08,822 - INFO - [Bar] fonction ajouter utilisée au temps 11.412086963653564
2023-10-04 21:01:08,822 - INFO - [Pic] fonction retirer utilisée au temps 11.412366390228271
2023-10-04 21:01:09,823 - INFO - [Pic] fonction ajouter utilisée au temps 12.41322135925293
2023-10-04 21:01:09,824 - INFO - [Barman] fonction prepare utilisée au temps 12.413936614990234
2023-10-04 21:01:09,825 - INFO - [Bar] fonction ajouter utilisée au temps 12.414454460144043
2023-10-04 21:01:09,825 - INFO - [Pic] fonction retirer utilisée au temps 12.414832592010498
2023-10-04 21:01:10,822 - INFO - [Bar] fonction retirer utilisée au temps 13.411917209625244
2023-10-04 21:01:10,823 - INFO - [Serveur] fonction servir utilisée au temps 13.412371158599854
2023-10-04 21:01:10,827 - INFO - [Barman] fonction prepare utilisée au temps 13.416398525238037
2023-10-04 21:01:10,827 - INFO - [Bar] fonction ajouter utilisée au temps 13.416897296905518
2023-10-04 21:01:11,825 - INFO - [Bar] fonction retirer utilisée au temps 14.414934635162354
2023-10-04 21:01:11,826 - INFO - [Serveur] fonction servir utilisée au temps 14.415448188781738
2023-10-04 21:01:12,827 - INFO - [Bar] fonction retirer utilisée au temps 15.416908740997314
2023-10-04 21:01:12,827 - INFO - [Serveur] fonction servir utilisée au temps 15.417282581329346
2023-10-04 21:04:48,953 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Serveur.servir() done, defined at /home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py:134> exception=SystemExit()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 140, in servir
    await asyncio.sleep(self.bar.tp + self.pic.tc ) # Attendre un peu la commande va arriver sur le bar
  File "/usr/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 151, in servir
    sys.exit()
SystemExit
